name: Deploy Upload Service

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip application
        run: zip -r upload.zip .

      - name: Upload to S3
        run: |
          aws s3 cp upload.zip s3://file-validation-artifacts-12345/upload.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1